# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `DeliverCardJob`.
# Please instead update this file by running `bin/tapioca dsl DeliverCardJob`.


class DeliverCardJob
  class << self
    sig do
      params(
        card_external_id: T.untyped,
        recipient_email: T.untyped,
        scheduled_for: T.untyped,
        block: T.nilable(T.proc.params(job: DeliverCardJob).void)
      ).returns(T.any(DeliverCardJob, FalseClass))
    end
    def perform_later(card_external_id, recipient_email, scheduled_for, &block); end

    sig do
      params(
        card_external_id: T.untyped,
        recipient_email: T.untyped,
        scheduled_for: T.untyped
      ).returns(T.untyped)
    end
    def perform_now(card_external_id, recipient_email, scheduled_for); end
  end
end
