# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `GenerateInvitationDraftJob`.
# Please instead update this file by running `bin/tapioca dsl GenerateInvitationDraftJob`.


class GenerateInvitationDraftJob
  class << self
    sig do
      params(
        user_id: T.untyped,
        prompt: T.untyped,
        options: T.untyped,
        block: T.nilable(T.proc.params(job: GenerateInvitationDraftJob).void)
      ).returns(T.any(GenerateInvitationDraftJob, FalseClass))
    end
    def perform_later(user_id:, prompt:, options: T.unsafe(nil), &block); end

    sig { params(user_id: T.untyped, prompt: T.untyped, options: T.untyped).returns(T.untyped) }
    def perform_now(user_id:, prompt:, options: T.unsafe(nil)); end
  end
end
