# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `HolidayCardMailOrder`.
# Please instead update this file by running `bin/tapioca dsl HolidayCardMailOrder`.


class HolidayCardMailOrder
  include GeneratedAssociationMethods
  include GeneratedAttributeMethods
  extend CommonRelationMethods
  extend GeneratedRelationMethods

  private

  sig { returns(NilClass) }
  def to_ary; end

  class << self
    sig do
      params(
        attributes: T.untyped,
        block: T.nilable(T.proc.params(object: ::HolidayCardMailOrder).void)
      ).returns(::HolidayCardMailOrder)
    end
    def new(attributes = nil, &block); end
  end

  module CommonRelationMethods
    sig do
      params(
        block: T.nilable(T.proc.params(record: ::HolidayCardMailOrder).returns(T.untyped))
      ).returns(T::Boolean)
    end
    def any?(&block); end

    sig { params(column_name: T.any(String, Symbol)).returns(T.any(Integer, Float, BigDecimal)) }
    def average(column_name); end

    sig do
      params(
        block: T.nilable(T.proc.params(object: ::HolidayCardMailOrder).void)
      ).returns(::HolidayCardMailOrder)
    end
    sig do
      params(
        attributes: T::Array[T.untyped],
        block: T.nilable(T.proc.params(object: ::HolidayCardMailOrder).void)
      ).returns(T::Array[::HolidayCardMailOrder])
    end
    sig do
      params(
        attributes: T.untyped,
        block: T.nilable(T.proc.params(object: ::HolidayCardMailOrder).void)
      ).returns(::HolidayCardMailOrder)
    end
    def build(attributes = nil, &block); end

    sig { params(operation: Symbol, column_name: T.any(String, Symbol)).returns(T.any(Integer, Float, BigDecimal)) }
    def calculate(operation, column_name); end

    sig { params(column_name: T.nilable(T.any(String, Symbol))).returns(Integer) }
    sig { params(column_name: NilClass, block: T.proc.params(object: ::HolidayCardMailOrder).void).returns(Integer) }
    def count(column_name = nil, &block); end

    sig do
      params(
        block: T.nilable(T.proc.params(object: ::HolidayCardMailOrder).void)
      ).returns(::HolidayCardMailOrder)
    end
    sig do
      params(
        attributes: T::Array[T.untyped],
        block: T.nilable(T.proc.params(object: ::HolidayCardMailOrder).void)
      ).returns(T::Array[::HolidayCardMailOrder])
    end
    sig do
      params(
        attributes: T.untyped,
        block: T.nilable(T.proc.params(object: ::HolidayCardMailOrder).void)
      ).returns(::HolidayCardMailOrder)
    end
    def create(attributes = nil, &block); end

    sig do
      params(
        block: T.nilable(T.proc.params(object: ::HolidayCardMailOrder).void)
      ).returns(::HolidayCardMailOrder)
    end
    sig do
      params(
        attributes: T::Array[T.untyped],
        block: T.nilable(T.proc.params(object: ::HolidayCardMailOrder).void)
      ).returns(T::Array[::HolidayCardMailOrder])
    end
    sig do
      params(
        attributes: T.untyped,
        block: T.nilable(T.proc.params(object: ::HolidayCardMailOrder).void)
      ).returns(::HolidayCardMailOrder)
    end
    def create!(attributes = nil, &block); end

    sig do
      params(
        attributes: T::Array[T.untyped],
        block: T.nilable(T.proc.params(object: ::HolidayCardMailOrder).void)
      ).returns(T::Array[::HolidayCardMailOrder])
    end
    sig do
      params(
        attributes: T.untyped,
        block: T.nilable(T.proc.params(object: ::HolidayCardMailOrder).void)
      ).returns(::HolidayCardMailOrder)
    end
    def create_or_find_by(attributes, &block); end

    sig do
      params(
        attributes: T::Array[T.untyped],
        block: T.nilable(T.proc.params(object: ::HolidayCardMailOrder).void)
      ).returns(T::Array[::HolidayCardMailOrder])
    end
    sig do
      params(
        attributes: T.untyped,
        block: T.nilable(T.proc.params(object: ::HolidayCardMailOrder).void)
      ).returns(::HolidayCardMailOrder)
    end
    def create_or_find_by!(attributes, &block); end

    sig { returns(T::Array[::HolidayCardMailOrder]) }
    def destroy_all; end

    sig { params(conditions: T.untyped).returns(T::Boolean) }
    def exists?(conditions = :none); end

    sig { returns(T.nilable(::HolidayCardMailOrder)) }
    def fifth; end

    sig { returns(::HolidayCardMailOrder) }
    def fifth!; end

    sig do
      params(
        args: T.any(String, Symbol, ::ActiveSupport::Multibyte::Chars, T::Boolean, BigDecimal, Numeric, ::ActiveRecord::Type::Binary::Data, ::ActiveRecord::Type::Time::Value, Date, Time, ::ActiveSupport::Duration, T::Class[T.anything])
      ).returns(::HolidayCardMailOrder)
    end
    sig do
      params(
        args: T::Array[T.any(String, Symbol, ::ActiveSupport::Multibyte::Chars, T::Boolean, BigDecimal, Numeric, ::ActiveRecord::Type::Binary::Data, ::ActiveRecord::Type::Time::Value, Date, Time, ::ActiveSupport::Duration, T::Class[T.anything])]
      ).returns(T::Enumerable[::HolidayCardMailOrder])
    end
    sig do
      params(
        args: NilClass,
        block: T.proc.params(object: ::HolidayCardMailOrder).void
      ).returns(T.nilable(::HolidayCardMailOrder))
    end
    def find(args = nil, &block); end

    sig { params(args: T.untyped).returns(T.nilable(::HolidayCardMailOrder)) }
    def find_by(*args); end

    sig { params(args: T.untyped).returns(::HolidayCardMailOrder) }
    def find_by!(*args); end

    sig do
      params(
        start: T.untyped,
        finish: T.untyped,
        batch_size: Integer,
        error_on_ignore: T.untyped,
        order: Symbol,
        block: T.proc.params(object: ::HolidayCardMailOrder).void
      ).void
    end
    sig do
      params(
        start: T.untyped,
        finish: T.untyped,
        batch_size: Integer,
        error_on_ignore: T.untyped,
        order: Symbol
      ).returns(T::Enumerator[::HolidayCardMailOrder])
    end
    def find_each(start: nil, finish: nil, batch_size: 1000, error_on_ignore: nil, order: :asc, &block); end

    sig do
      params(
        start: T.untyped,
        finish: T.untyped,
        batch_size: Integer,
        error_on_ignore: T.untyped,
        order: Symbol,
        block: T.proc.params(object: T::Array[::HolidayCardMailOrder]).void
      ).void
    end
    sig do
      params(
        start: T.untyped,
        finish: T.untyped,
        batch_size: Integer,
        error_on_ignore: T.untyped,
        order: Symbol
      ).returns(T::Enumerator[T::Enumerator[::HolidayCardMailOrder]])
    end
    def find_in_batches(start: nil, finish: nil, batch_size: 1000, error_on_ignore: nil, order: :asc, &block); end

    sig do
      params(
        attributes: T::Array[T.untyped],
        block: T.nilable(T.proc.params(object: ::HolidayCardMailOrder).void)
      ).returns(T::Array[::HolidayCardMailOrder])
    end
    sig do
      params(
        attributes: T.untyped,
        block: T.nilable(T.proc.params(object: ::HolidayCardMailOrder).void)
      ).returns(::HolidayCardMailOrder)
    end
    def find_or_create_by(attributes, &block); end

    sig do
      params(
        attributes: T::Array[T.untyped],
        block: T.nilable(T.proc.params(object: ::HolidayCardMailOrder).void)
      ).returns(T::Array[::HolidayCardMailOrder])
    end
    sig do
      params(
        attributes: T.untyped,
        block: T.nilable(T.proc.params(object: ::HolidayCardMailOrder).void)
      ).returns(::HolidayCardMailOrder)
    end
    def find_or_create_by!(attributes, &block); end

    sig do
      params(
        attributes: T::Array[T.untyped],
        block: T.nilable(T.proc.params(object: ::HolidayCardMailOrder).void)
      ).returns(T::Array[::HolidayCardMailOrder])
    end
    sig do
      params(
        attributes: T.untyped,
        block: T.nilable(T.proc.params(object: ::HolidayCardMailOrder).void)
      ).returns(::HolidayCardMailOrder)
    end
    def find_or_initialize_by(attributes, &block); end

    sig { params(signed_id: T.untyped, purpose: T.untyped).returns(T.nilable(::HolidayCardMailOrder)) }
    def find_signed(signed_id, purpose: nil); end

    sig { params(signed_id: T.untyped, purpose: T.untyped).returns(::HolidayCardMailOrder) }
    def find_signed!(signed_id, purpose: nil); end

    sig { params(arg: T.untyped, args: T.untyped).returns(::HolidayCardMailOrder) }
    def find_sole_by(arg, *args); end

    sig { returns(T.nilable(::HolidayCardMailOrder)) }
    sig { params(limit: Integer).returns(T::Array[::HolidayCardMailOrder]) }
    def first(limit = nil); end

    sig { returns(::HolidayCardMailOrder) }
    def first!; end

    sig { returns(T.nilable(::HolidayCardMailOrder)) }
    def forty_two; end

    sig { returns(::HolidayCardMailOrder) }
    def forty_two!; end

    sig { returns(T.nilable(::HolidayCardMailOrder)) }
    def fourth; end

    sig { returns(::HolidayCardMailOrder) }
    def fourth!; end

    sig { returns(Array) }
    def ids; end

    sig do
      params(
        of: Integer,
        start: T.untyped,
        finish: T.untyped,
        load: T.untyped,
        error_on_ignore: T.untyped,
        order: Symbol,
        use_ranges: T.untyped,
        block: T.proc.params(object: PrivateRelation).void
      ).void
    end
    sig do
      params(
        of: Integer,
        start: T.untyped,
        finish: T.untyped,
        load: T.untyped,
        error_on_ignore: T.untyped,
        order: Symbol,
        use_ranges: T.untyped
      ).returns(::ActiveRecord::Batches::BatchEnumerator)
    end
    def in_batches(of: 1000, start: nil, finish: nil, load: false, error_on_ignore: nil, order: :asc, use_ranges: nil, &block); end

    sig { params(record: T.untyped).returns(T::Boolean) }
    def include?(record); end

    sig { returns(T.nilable(::HolidayCardMailOrder)) }
    sig { params(limit: Integer).returns(T::Array[::HolidayCardMailOrder]) }
    def last(limit = nil); end

    sig { returns(::HolidayCardMailOrder) }
    def last!; end

    sig do
      params(
        block: T.nilable(T.proc.params(record: ::HolidayCardMailOrder).returns(T.untyped))
      ).returns(T::Boolean)
    end
    def many?(&block); end

    sig { params(column_name: T.any(String, Symbol)).returns(T.untyped) }
    def maximum(column_name); end

    sig { params(record: T.untyped).returns(T::Boolean) }
    def member?(record); end

    sig { params(column_name: T.any(String, Symbol)).returns(T.untyped) }
    def minimum(column_name); end

    sig do
      params(
        block: T.nilable(T.proc.params(object: ::HolidayCardMailOrder).void)
      ).returns(::HolidayCardMailOrder)
    end
    sig do
      params(
        attributes: T::Array[T.untyped],
        block: T.nilable(T.proc.params(object: ::HolidayCardMailOrder).void)
      ).returns(T::Array[::HolidayCardMailOrder])
    end
    sig do
      params(
        attributes: T.untyped,
        block: T.nilable(T.proc.params(object: ::HolidayCardMailOrder).void)
      ).returns(::HolidayCardMailOrder)
    end
    def new(attributes = nil, &block); end

    sig do
      params(
        block: T.nilable(T.proc.params(record: ::HolidayCardMailOrder).returns(T.untyped))
      ).returns(T::Boolean)
    end
    def none?(&block); end

    sig do
      params(
        block: T.nilable(T.proc.params(record: ::HolidayCardMailOrder).returns(T.untyped))
      ).returns(T::Boolean)
    end
    def one?(&block); end

    sig { params(column_names: T.untyped).returns(T.untyped) }
    def pick(*column_names); end

    sig { params(column_names: T.untyped).returns(T.untyped) }
    def pluck(*column_names); end

    sig { returns(T.nilable(::HolidayCardMailOrder)) }
    def second; end

    sig { returns(::HolidayCardMailOrder) }
    def second!; end

    sig { returns(T.nilable(::HolidayCardMailOrder)) }
    def second_to_last; end

    sig { returns(::HolidayCardMailOrder) }
    def second_to_last!; end

    sig { returns(::HolidayCardMailOrder) }
    def sole; end

    sig { params(initial_value_or_column: T.untyped).returns(T.any(Integer, Float, BigDecimal)) }
    sig do
      type_parameters(:U)
        .params(
          initial_value_or_column: T.nilable(T.type_parameter(:U)),
          block: T.proc.params(object: ::HolidayCardMailOrder).returns(T.type_parameter(:U))
        ).returns(T.type_parameter(:U))
    end
    def sum(initial_value_or_column = nil, &block); end

    sig { returns(T.nilable(::HolidayCardMailOrder)) }
    sig { params(limit: Integer).returns(T::Array[::HolidayCardMailOrder]) }
    def take(limit = nil); end

    sig { returns(::HolidayCardMailOrder) }
    def take!; end

    sig { returns(T.nilable(::HolidayCardMailOrder)) }
    def third; end

    sig { returns(::HolidayCardMailOrder) }
    def third!; end

    sig { returns(T.nilable(::HolidayCardMailOrder)) }
    def third_to_last; end

    sig { returns(::HolidayCardMailOrder) }
    def third_to_last!; end
  end

  module GeneratedAssociationMethods
    sig { params(args: T.untyped, blk: T.untyped).returns(::Contact) }
    def build_contact(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(::HolidayCard) }
    def build_holiday_card(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(::PostageCredit) }
    def build_postage_credit(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(::User) }
    def build_user(*args, &blk); end

    sig { returns(T.nilable(::Contact)) }
    def contact; end

    sig { params(value: T.nilable(::Contact)).void }
    def contact=(value); end

    sig { returns(T::Boolean) }
    def contact_changed?; end

    sig { returns(T::Boolean) }
    def contact_previously_changed?; end

    sig { params(args: T.untyped, blk: T.untyped).returns(::Contact) }
    def create_contact(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(::Contact) }
    def create_contact!(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(::HolidayCard) }
    def create_holiday_card(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(::HolidayCard) }
    def create_holiday_card!(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(::PostageCredit) }
    def create_postage_credit(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(::PostageCredit) }
    def create_postage_credit!(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(::User) }
    def create_user(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(::User) }
    def create_user!(*args, &blk); end

    sig { returns(T.nilable(::HolidayCard)) }
    def holiday_card; end

    sig { params(value: T.nilable(::HolidayCard)).void }
    def holiday_card=(value); end

    sig { returns(T::Boolean) }
    def holiday_card_changed?; end

    sig { returns(T::Boolean) }
    def holiday_card_previously_changed?; end

    sig { returns(T.nilable(::PostageCredit)) }
    def postage_credit; end

    sig { params(value: T.nilable(::PostageCredit)).void }
    def postage_credit=(value); end

    sig { returns(T::Boolean) }
    def postage_credit_changed?; end

    sig { returns(T::Boolean) }
    def postage_credit_previously_changed?; end

    sig { returns(T.nilable(::Contact)) }
    def reload_contact; end

    sig { returns(T.nilable(::HolidayCard)) }
    def reload_holiday_card; end

    sig { returns(T.nilable(::PostageCredit)) }
    def reload_postage_credit; end

    sig { returns(T.nilable(::User)) }
    def reload_user; end

    sig { void }
    def reset_contact; end

    sig { void }
    def reset_holiday_card; end

    sig { void }
    def reset_postage_credit; end

    sig { void }
    def reset_user; end

    sig { returns(T.nilable(::User)) }
    def user; end

    sig { params(value: T.nilable(::User)).void }
    def user=(value); end

    sig { returns(T::Boolean) }
    def user_changed?; end

    sig { returns(T::Boolean) }
    def user_previously_changed?; end
  end

  module GeneratedAssociationRelationMethods
    sig { returns(PrivateAssociationRelation) }
    def all; end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def and(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def annotate(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def arel_columns(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def create_with(*args, &blk); end

    sig { params(value: T::Boolean).returns(PrivateAssociationRelation) }
    def distinct(value = true); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def eager_load(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def except(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def excluding(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def extending(*args, &blk); end

    sig { params(association: Symbol).returns(T::Array[T.untyped]) }
    def extract_associated(association); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def for_card(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def from(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelationGroupChain) }
    def group(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def having(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def in_order_of(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def includes(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def invert_where(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def joins(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def left_joins(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def left_outer_joins(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def limit(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def lock(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def merge(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def newest_first(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def none(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def null_relation?(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def offset(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def only(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def optimizer_hints(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def or(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def order(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def preload(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def readonly(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def references(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def regroup(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def reorder(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def reselect(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def reverse_order(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def rewhere(*args, &blk); end

    sig { params(args: T.untyped).returns(PrivateAssociationRelation) }
    sig do
      params(
        blk: T.proc.params(record: ::HolidayCardMailOrder).returns(BasicObject)
      ).returns(T::Array[::HolidayCardMailOrder])
    end
    def select(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def strict_loading(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def structurally_compatible?(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def uniq!(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def unscope(*args, &blk); end

    sig { returns(PrivateAssociationRelationWhereChain) }
    sig { params(args: T.untyped).returns(PrivateAssociationRelation) }
    def where(*args); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def with(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def with_recursive(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateAssociationRelation) }
    def without(*args, &blk); end
  end

  module GeneratedAttributeMethods
    sig { returns(::Integer) }
    def base_cents; end

    sig { params(value: ::Integer).returns(::Integer) }
    def base_cents=(value); end

    sig { returns(T::Boolean) }
    def base_cents?; end

    sig { returns(T.nilable(::Integer)) }
    def base_cents_before_last_save; end

    sig { returns(T.untyped) }
    def base_cents_before_type_cast; end

    sig { returns(T::Boolean) }
    def base_cents_came_from_user?; end

    sig { returns(T.nilable([::Integer, ::Integer])) }
    def base_cents_change; end

    sig { returns(T.nilable([::Integer, ::Integer])) }
    def base_cents_change_to_be_saved; end

    sig { params(from: ::Integer, to: ::Integer).returns(T::Boolean) }
    def base_cents_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::Integer)) }
    def base_cents_in_database; end

    sig { returns(T.nilable([::Integer, ::Integer])) }
    def base_cents_previous_change; end

    sig { params(from: ::Integer, to: ::Integer).returns(T::Boolean) }
    def base_cents_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::Integer)) }
    def base_cents_previously_was; end

    sig { returns(T.nilable(::Integer)) }
    def base_cents_was; end

    sig { void }
    def base_cents_will_change!; end

    sig { returns(::Integer) }
    def charged_cents; end

    sig { params(value: ::Integer).returns(::Integer) }
    def charged_cents=(value); end

    sig { returns(T::Boolean) }
    def charged_cents?; end

    sig { returns(T.nilable(::Integer)) }
    def charged_cents_before_last_save; end

    sig { returns(T.untyped) }
    def charged_cents_before_type_cast; end

    sig { returns(T::Boolean) }
    def charged_cents_came_from_user?; end

    sig { returns(T.nilable([::Integer, ::Integer])) }
    def charged_cents_change; end

    sig { returns(T.nilable([::Integer, ::Integer])) }
    def charged_cents_change_to_be_saved; end

    sig { params(from: ::Integer, to: ::Integer).returns(T::Boolean) }
    def charged_cents_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::Integer)) }
    def charged_cents_in_database; end

    sig { returns(T.nilable([::Integer, ::Integer])) }
    def charged_cents_previous_change; end

    sig { params(from: ::Integer, to: ::Integer).returns(T::Boolean) }
    def charged_cents_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::Integer)) }
    def charged_cents_previously_was; end

    sig { returns(T.nilable(::Integer)) }
    def charged_cents_was; end

    sig { void }
    def charged_cents_will_change!; end

    sig { returns(T.nilable(::Integer)) }
    def contact_id; end

    sig { params(value: T.nilable(::Integer)).returns(T.nilable(::Integer)) }
    def contact_id=(value); end

    sig { returns(T::Boolean) }
    def contact_id?; end

    sig { returns(T.nilable(::Integer)) }
    def contact_id_before_last_save; end

    sig { returns(T.untyped) }
    def contact_id_before_type_cast; end

    sig { returns(T::Boolean) }
    def contact_id_came_from_user?; end

    sig { returns(T.nilable([T.nilable(::Integer), T.nilable(::Integer)])) }
    def contact_id_change; end

    sig { returns(T.nilable([T.nilable(::Integer), T.nilable(::Integer)])) }
    def contact_id_change_to_be_saved; end

    sig { params(from: T.nilable(::Integer), to: T.nilable(::Integer)).returns(T::Boolean) }
    def contact_id_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::Integer)) }
    def contact_id_in_database; end

    sig { returns(T.nilable([T.nilable(::Integer), T.nilable(::Integer)])) }
    def contact_id_previous_change; end

    sig { params(from: T.nilable(::Integer), to: T.nilable(::Integer)).returns(T::Boolean) }
    def contact_id_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::Integer)) }
    def contact_id_previously_was; end

    sig { returns(T.nilable(::Integer)) }
    def contact_id_was; end

    sig { void }
    def contact_id_will_change!; end

    sig { returns(::ActiveSupport::TimeWithZone) }
    def created_at; end

    sig { params(value: ::ActiveSupport::TimeWithZone).returns(::ActiveSupport::TimeWithZone) }
    def created_at=(value); end

    sig { returns(T::Boolean) }
    def created_at?; end

    sig { returns(T.nilable(::ActiveSupport::TimeWithZone)) }
    def created_at_before_last_save; end

    sig { returns(T.untyped) }
    def created_at_before_type_cast; end

    sig { returns(T::Boolean) }
    def created_at_came_from_user?; end

    sig { returns(T.nilable([::ActiveSupport::TimeWithZone, ::ActiveSupport::TimeWithZone])) }
    def created_at_change; end

    sig { returns(T.nilable([::ActiveSupport::TimeWithZone, ::ActiveSupport::TimeWithZone])) }
    def created_at_change_to_be_saved; end

    sig { params(from: ::ActiveSupport::TimeWithZone, to: ::ActiveSupport::TimeWithZone).returns(T::Boolean) }
    def created_at_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::ActiveSupport::TimeWithZone)) }
    def created_at_in_database; end

    sig { returns(T.nilable([::ActiveSupport::TimeWithZone, ::ActiveSupport::TimeWithZone])) }
    def created_at_previous_change; end

    sig { params(from: ::ActiveSupport::TimeWithZone, to: ::ActiveSupport::TimeWithZone).returns(T::Boolean) }
    def created_at_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::ActiveSupport::TimeWithZone)) }
    def created_at_previously_was; end

    sig { returns(T.nilable(::ActiveSupport::TimeWithZone)) }
    def created_at_was; end

    sig { void }
    def created_at_will_change!; end

    sig { returns(T.nilable(::String)) }
    def failure_reason; end

    sig { params(value: T.nilable(::String)).returns(T.nilable(::String)) }
    def failure_reason=(value); end

    sig { returns(T::Boolean) }
    def failure_reason?; end

    sig { returns(T.nilable(::String)) }
    def failure_reason_before_last_save; end

    sig { returns(T.untyped) }
    def failure_reason_before_type_cast; end

    sig { returns(T::Boolean) }
    def failure_reason_came_from_user?; end

    sig { returns(T.nilable([T.nilable(::String), T.nilable(::String)])) }
    def failure_reason_change; end

    sig { returns(T.nilable([T.nilable(::String), T.nilable(::String)])) }
    def failure_reason_change_to_be_saved; end

    sig { params(from: T.nilable(::String), to: T.nilable(::String)).returns(T::Boolean) }
    def failure_reason_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def failure_reason_in_database; end

    sig { returns(T.nilable([T.nilable(::String), T.nilable(::String)])) }
    def failure_reason_previous_change; end

    sig { params(from: T.nilable(::String), to: T.nilable(::String)).returns(T::Boolean) }
    def failure_reason_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def failure_reason_previously_was; end

    sig { returns(T.nilable(::String)) }
    def failure_reason_was; end

    sig { void }
    def failure_reason_will_change!; end

    sig { returns(::Integer) }
    def holiday_card_id; end

    sig { params(value: ::Integer).returns(::Integer) }
    def holiday_card_id=(value); end

    sig { returns(T::Boolean) }
    def holiday_card_id?; end

    sig { returns(T.nilable(::Integer)) }
    def holiday_card_id_before_last_save; end

    sig { returns(T.untyped) }
    def holiday_card_id_before_type_cast; end

    sig { returns(T::Boolean) }
    def holiday_card_id_came_from_user?; end

    sig { returns(T.nilable([::Integer, ::Integer])) }
    def holiday_card_id_change; end

    sig { returns(T.nilable([::Integer, ::Integer])) }
    def holiday_card_id_change_to_be_saved; end

    sig { params(from: ::Integer, to: ::Integer).returns(T::Boolean) }
    def holiday_card_id_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::Integer)) }
    def holiday_card_id_in_database; end

    sig { returns(T.nilable([::Integer, ::Integer])) }
    def holiday_card_id_previous_change; end

    sig { params(from: ::Integer, to: ::Integer).returns(T::Boolean) }
    def holiday_card_id_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::Integer)) }
    def holiday_card_id_previously_was; end

    sig { returns(T.nilable(::Integer)) }
    def holiday_card_id_was; end

    sig { void }
    def holiday_card_id_will_change!; end

    sig { returns(::Integer) }
    def id; end

    sig { params(value: ::Integer).returns(::Integer) }
    def id=(value); end

    sig { returns(T::Boolean) }
    def id?; end

    sig { returns(T.nilable(::Integer)) }
    def id_before_last_save; end

    sig { returns(T.untyped) }
    def id_before_type_cast; end

    sig { returns(T::Boolean) }
    def id_came_from_user?; end

    sig { returns(T.nilable([::Integer, ::Integer])) }
    def id_change; end

    sig { returns(T.nilable([::Integer, ::Integer])) }
    def id_change_to_be_saved; end

    sig { params(from: ::Integer, to: ::Integer).returns(T::Boolean) }
    def id_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::Integer)) }
    def id_in_database; end

    sig { returns(T.nilable([::Integer, ::Integer])) }
    def id_previous_change; end

    sig { params(from: ::Integer, to: ::Integer).returns(T::Boolean) }
    def id_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::Integer)) }
    def id_previously_was; end

    sig { returns(::Integer) }
    def id_value; end

    sig { params(value: ::Integer).returns(::Integer) }
    def id_value=(value); end

    sig { returns(T::Boolean) }
    def id_value?; end

    sig { returns(T.nilable(::Integer)) }
    def id_value_before_last_save; end

    sig { returns(T.untyped) }
    def id_value_before_type_cast; end

    sig { returns(T::Boolean) }
    def id_value_came_from_user?; end

    sig { returns(T.nilable([::Integer, ::Integer])) }
    def id_value_change; end

    sig { returns(T.nilable([::Integer, ::Integer])) }
    def id_value_change_to_be_saved; end

    sig { params(from: ::Integer, to: ::Integer).returns(T::Boolean) }
    def id_value_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::Integer)) }
    def id_value_in_database; end

    sig { returns(T.nilable([::Integer, ::Integer])) }
    def id_value_previous_change; end

    sig { params(from: ::Integer, to: ::Integer).returns(T::Boolean) }
    def id_value_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::Integer)) }
    def id_value_previously_was; end

    sig { returns(T.nilable(::Integer)) }
    def id_value_was; end

    sig { void }
    def id_value_will_change!; end

    sig { returns(T.nilable(::Integer)) }
    def id_was; end

    sig { void }
    def id_will_change!; end

    sig { returns(::String) }
    def idempotency_key; end

    sig { params(value: ::String).returns(::String) }
    def idempotency_key=(value); end

    sig { returns(T::Boolean) }
    def idempotency_key?; end

    sig { returns(T.nilable(::String)) }
    def idempotency_key_before_last_save; end

    sig { returns(T.untyped) }
    def idempotency_key_before_type_cast; end

    sig { returns(T::Boolean) }
    def idempotency_key_came_from_user?; end

    sig { returns(T.nilable([::String, ::String])) }
    def idempotency_key_change; end

    sig { returns(T.nilable([::String, ::String])) }
    def idempotency_key_change_to_be_saved; end

    sig { params(from: ::String, to: ::String).returns(T::Boolean) }
    def idempotency_key_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def idempotency_key_in_database; end

    sig { returns(T.nilable([::String, ::String])) }
    def idempotency_key_previous_change; end

    sig { params(from: ::String, to: ::String).returns(T::Boolean) }
    def idempotency_key_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def idempotency_key_previously_was; end

    sig { returns(T.nilable(::String)) }
    def idempotency_key_was; end

    sig { void }
    def idempotency_key_will_change!; end

    sig { returns(T.nilable(::ActiveSupport::TimeWithZone)) }
    def mailed_at; end

    sig { params(value: T.nilable(::ActiveSupport::TimeWithZone)).returns(T.nilable(::ActiveSupport::TimeWithZone)) }
    def mailed_at=(value); end

    sig { returns(T::Boolean) }
    def mailed_at?; end

    sig { returns(T.nilable(::ActiveSupport::TimeWithZone)) }
    def mailed_at_before_last_save; end

    sig { returns(T.untyped) }
    def mailed_at_before_type_cast; end

    sig { returns(T::Boolean) }
    def mailed_at_came_from_user?; end

    sig { returns(T.nilable([T.nilable(::ActiveSupport::TimeWithZone), T.nilable(::ActiveSupport::TimeWithZone)])) }
    def mailed_at_change; end

    sig { returns(T.nilable([T.nilable(::ActiveSupport::TimeWithZone), T.nilable(::ActiveSupport::TimeWithZone)])) }
    def mailed_at_change_to_be_saved; end

    sig do
      params(
        from: T.nilable(::ActiveSupport::TimeWithZone),
        to: T.nilable(::ActiveSupport::TimeWithZone)
      ).returns(T::Boolean)
    end
    def mailed_at_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::ActiveSupport::TimeWithZone)) }
    def mailed_at_in_database; end

    sig { returns(T.nilable([T.nilable(::ActiveSupport::TimeWithZone), T.nilable(::ActiveSupport::TimeWithZone)])) }
    def mailed_at_previous_change; end

    sig do
      params(
        from: T.nilable(::ActiveSupport::TimeWithZone),
        to: T.nilable(::ActiveSupport::TimeWithZone)
      ).returns(T::Boolean)
    end
    def mailed_at_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::ActiveSupport::TimeWithZone)) }
    def mailed_at_previously_was; end

    sig { returns(T.nilable(::ActiveSupport::TimeWithZone)) }
    def mailed_at_was; end

    sig { void }
    def mailed_at_will_change!; end

    sig { returns(::String) }
    def mailing_class; end

    sig { params(value: ::String).returns(::String) }
    def mailing_class=(value); end

    sig { returns(T::Boolean) }
    def mailing_class?; end

    sig { returns(T.nilable(::String)) }
    def mailing_class_before_last_save; end

    sig { returns(T.untyped) }
    def mailing_class_before_type_cast; end

    sig { returns(T::Boolean) }
    def mailing_class_came_from_user?; end

    sig { returns(T.nilable([::String, ::String])) }
    def mailing_class_change; end

    sig { returns(T.nilable([::String, ::String])) }
    def mailing_class_change_to_be_saved; end

    sig { params(from: ::String, to: ::String).returns(T::Boolean) }
    def mailing_class_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def mailing_class_in_database; end

    sig { returns(T.nilable([::String, ::String])) }
    def mailing_class_previous_change; end

    sig { params(from: ::String, to: ::String).returns(T::Boolean) }
    def mailing_class_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def mailing_class_previously_was; end

    sig { returns(T.nilable(::String)) }
    def mailing_class_was; end

    sig { void }
    def mailing_class_will_change!; end

    sig { returns(T.nilable(::Integer)) }
    def postage_credit_id; end

    sig { params(value: T.nilable(::Integer)).returns(T.nilable(::Integer)) }
    def postage_credit_id=(value); end

    sig { returns(T::Boolean) }
    def postage_credit_id?; end

    sig { returns(T.nilable(::Integer)) }
    def postage_credit_id_before_last_save; end

    sig { returns(T.untyped) }
    def postage_credit_id_before_type_cast; end

    sig { returns(T::Boolean) }
    def postage_credit_id_came_from_user?; end

    sig { returns(T.nilable([T.nilable(::Integer), T.nilable(::Integer)])) }
    def postage_credit_id_change; end

    sig { returns(T.nilable([T.nilable(::Integer), T.nilable(::Integer)])) }
    def postage_credit_id_change_to_be_saved; end

    sig { params(from: T.nilable(::Integer), to: T.nilable(::Integer)).returns(T::Boolean) }
    def postage_credit_id_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::Integer)) }
    def postage_credit_id_in_database; end

    sig { returns(T.nilable([T.nilable(::Integer), T.nilable(::Integer)])) }
    def postage_credit_id_previous_change; end

    sig { params(from: T.nilable(::Integer), to: T.nilable(::Integer)).returns(T::Boolean) }
    def postage_credit_id_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::Integer)) }
    def postage_credit_id_previously_was; end

    sig { returns(T.nilable(::Integer)) }
    def postage_credit_id_was; end

    sig { void }
    def postage_credit_id_will_change!; end

    sig { returns(T.nilable(::String)) }
    def postgrid_id; end

    sig { params(value: T.nilable(::String)).returns(T.nilable(::String)) }
    def postgrid_id=(value); end

    sig { returns(T::Boolean) }
    def postgrid_id?; end

    sig { returns(T.nilable(::String)) }
    def postgrid_id_before_last_save; end

    sig { returns(T.untyped) }
    def postgrid_id_before_type_cast; end

    sig { returns(T::Boolean) }
    def postgrid_id_came_from_user?; end

    sig { returns(T.nilable([T.nilable(::String), T.nilable(::String)])) }
    def postgrid_id_change; end

    sig { returns(T.nilable([T.nilable(::String), T.nilable(::String)])) }
    def postgrid_id_change_to_be_saved; end

    sig { params(from: T.nilable(::String), to: T.nilable(::String)).returns(T::Boolean) }
    def postgrid_id_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def postgrid_id_in_database; end

    sig { returns(T.nilable([T.nilable(::String), T.nilable(::String)])) }
    def postgrid_id_previous_change; end

    sig { params(from: T.nilable(::String), to: T.nilable(::String)).returns(T::Boolean) }
    def postgrid_id_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def postgrid_id_previously_was; end

    sig { returns(T.nilable(::String)) }
    def postgrid_id_was; end

    sig { void }
    def postgrid_id_will_change!; end

    sig { returns(::String) }
    def rate_card_version; end

    sig { params(value: ::String).returns(::String) }
    def rate_card_version=(value); end

    sig { returns(T::Boolean) }
    def rate_card_version?; end

    sig { returns(T.nilable(::String)) }
    def rate_card_version_before_last_save; end

    sig { returns(T.untyped) }
    def rate_card_version_before_type_cast; end

    sig { returns(T::Boolean) }
    def rate_card_version_came_from_user?; end

    sig { returns(T.nilable([::String, ::String])) }
    def rate_card_version_change; end

    sig { returns(T.nilable([::String, ::String])) }
    def rate_card_version_change_to_be_saved; end

    sig { params(from: ::String, to: ::String).returns(T::Boolean) }
    def rate_card_version_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def rate_card_version_in_database; end

    sig { returns(T.nilable([::String, ::String])) }
    def rate_card_version_previous_change; end

    sig { params(from: ::String, to: ::String).returns(T::Boolean) }
    def rate_card_version_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def rate_card_version_previously_was; end

    sig { returns(T.nilable(::String)) }
    def rate_card_version_was; end

    sig { void }
    def rate_card_version_will_change!; end

    sig { returns(T.untyped) }
    def recipient_snapshot; end

    sig { params(value: T.untyped).returns(T.untyped) }
    def recipient_snapshot=(value); end

    sig { returns(T::Boolean) }
    def recipient_snapshot?; end

    sig { returns(T.untyped) }
    def recipient_snapshot_before_last_save; end

    sig { returns(T.untyped) }
    def recipient_snapshot_before_type_cast; end

    sig { returns(T::Boolean) }
    def recipient_snapshot_came_from_user?; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def recipient_snapshot_change; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def recipient_snapshot_change_to_be_saved; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def recipient_snapshot_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.untyped) }
    def recipient_snapshot_in_database; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def recipient_snapshot_previous_change; end

    sig { params(from: T.untyped, to: T.untyped).returns(T::Boolean) }
    def recipient_snapshot_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.untyped) }
    def recipient_snapshot_previously_was; end

    sig { returns(T.untyped) }
    def recipient_snapshot_was; end

    sig { void }
    def recipient_snapshot_will_change!; end

    sig { void }
    def restore_base_cents!; end

    sig { void }
    def restore_charged_cents!; end

    sig { void }
    def restore_contact_id!; end

    sig { void }
    def restore_created_at!; end

    sig { void }
    def restore_failure_reason!; end

    sig { void }
    def restore_holiday_card_id!; end

    sig { void }
    def restore_id!; end

    sig { void }
    def restore_id_value!; end

    sig { void }
    def restore_idempotency_key!; end

    sig { void }
    def restore_mailed_at!; end

    sig { void }
    def restore_mailing_class!; end

    sig { void }
    def restore_postage_credit_id!; end

    sig { void }
    def restore_postgrid_id!; end

    sig { void }
    def restore_rate_card_version!; end

    sig { void }
    def restore_recipient_snapshot!; end

    sig { void }
    def restore_size!; end

    sig { void }
    def restore_status!; end

    sig { void }
    def restore_submitted_at!; end

    sig { void }
    def restore_tracking_number!; end

    sig { void }
    def restore_updated_at!; end

    sig { void }
    def restore_user_id!; end

    sig { void }
    def restore_zone!; end

    sig { returns(T.nilable([::Integer, ::Integer])) }
    def saved_change_to_base_cents; end

    sig { returns(T::Boolean) }
    def saved_change_to_base_cents?; end

    sig { returns(T.nilable([::Integer, ::Integer])) }
    def saved_change_to_charged_cents; end

    sig { returns(T::Boolean) }
    def saved_change_to_charged_cents?; end

    sig { returns(T.nilable([T.nilable(::Integer), T.nilable(::Integer)])) }
    def saved_change_to_contact_id; end

    sig { returns(T::Boolean) }
    def saved_change_to_contact_id?; end

    sig { returns(T.nilable([::ActiveSupport::TimeWithZone, ::ActiveSupport::TimeWithZone])) }
    def saved_change_to_created_at; end

    sig { returns(T::Boolean) }
    def saved_change_to_created_at?; end

    sig { returns(T.nilable([T.nilable(::String), T.nilable(::String)])) }
    def saved_change_to_failure_reason; end

    sig { returns(T::Boolean) }
    def saved_change_to_failure_reason?; end

    sig { returns(T.nilable([::Integer, ::Integer])) }
    def saved_change_to_holiday_card_id; end

    sig { returns(T::Boolean) }
    def saved_change_to_holiday_card_id?; end

    sig { returns(T.nilable([::Integer, ::Integer])) }
    def saved_change_to_id; end

    sig { returns(T::Boolean) }
    def saved_change_to_id?; end

    sig { returns(T.nilable([::Integer, ::Integer])) }
    def saved_change_to_id_value; end

    sig { returns(T::Boolean) }
    def saved_change_to_id_value?; end

    sig { returns(T.nilable([::String, ::String])) }
    def saved_change_to_idempotency_key; end

    sig { returns(T::Boolean) }
    def saved_change_to_idempotency_key?; end

    sig { returns(T.nilable([T.nilable(::ActiveSupport::TimeWithZone), T.nilable(::ActiveSupport::TimeWithZone)])) }
    def saved_change_to_mailed_at; end

    sig { returns(T::Boolean) }
    def saved_change_to_mailed_at?; end

    sig { returns(T.nilable([::String, ::String])) }
    def saved_change_to_mailing_class; end

    sig { returns(T::Boolean) }
    def saved_change_to_mailing_class?; end

    sig { returns(T.nilable([T.nilable(::Integer), T.nilable(::Integer)])) }
    def saved_change_to_postage_credit_id; end

    sig { returns(T::Boolean) }
    def saved_change_to_postage_credit_id?; end

    sig { returns(T.nilable([T.nilable(::String), T.nilable(::String)])) }
    def saved_change_to_postgrid_id; end

    sig { returns(T::Boolean) }
    def saved_change_to_postgrid_id?; end

    sig { returns(T.nilable([::String, ::String])) }
    def saved_change_to_rate_card_version; end

    sig { returns(T::Boolean) }
    def saved_change_to_rate_card_version?; end

    sig { returns(T.nilable([T.untyped, T.untyped])) }
    def saved_change_to_recipient_snapshot; end

    sig { returns(T::Boolean) }
    def saved_change_to_recipient_snapshot?; end

    sig { returns(T.nilable([::String, ::String])) }
    def saved_change_to_size; end

    sig { returns(T::Boolean) }
    def saved_change_to_size?; end

    sig { returns(T.nilable([::String, ::String])) }
    def saved_change_to_status; end

    sig { returns(T::Boolean) }
    def saved_change_to_status?; end

    sig { returns(T.nilable([T.nilable(::ActiveSupport::TimeWithZone), T.nilable(::ActiveSupport::TimeWithZone)])) }
    def saved_change_to_submitted_at; end

    sig { returns(T::Boolean) }
    def saved_change_to_submitted_at?; end

    sig { returns(T.nilable([T.nilable(::String), T.nilable(::String)])) }
    def saved_change_to_tracking_number; end

    sig { returns(T::Boolean) }
    def saved_change_to_tracking_number?; end

    sig { returns(T.nilable([::ActiveSupport::TimeWithZone, ::ActiveSupport::TimeWithZone])) }
    def saved_change_to_updated_at; end

    sig { returns(T::Boolean) }
    def saved_change_to_updated_at?; end

    sig { returns(T.nilable([::Integer, ::Integer])) }
    def saved_change_to_user_id; end

    sig { returns(T::Boolean) }
    def saved_change_to_user_id?; end

    sig { returns(T.nilable([::String, ::String])) }
    def saved_change_to_zone; end

    sig { returns(T::Boolean) }
    def saved_change_to_zone?; end

    sig { returns(::String) }
    def size; end

    sig { params(value: ::String).returns(::String) }
    def size=(value); end

    sig { returns(T::Boolean) }
    def size?; end

    sig { returns(T.nilable(::String)) }
    def size_before_last_save; end

    sig { returns(T.untyped) }
    def size_before_type_cast; end

    sig { returns(T::Boolean) }
    def size_came_from_user?; end

    sig { returns(T.nilable([::String, ::String])) }
    def size_change; end

    sig { returns(T.nilable([::String, ::String])) }
    def size_change_to_be_saved; end

    sig { params(from: ::String, to: ::String).returns(T::Boolean) }
    def size_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def size_in_database; end

    sig { returns(T.nilable([::String, ::String])) }
    def size_previous_change; end

    sig { params(from: ::String, to: ::String).returns(T::Boolean) }
    def size_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def size_previously_was; end

    sig { returns(T.nilable(::String)) }
    def size_was; end

    sig { void }
    def size_will_change!; end

    sig { returns(::String) }
    def status; end

    sig { params(value: ::String).returns(::String) }
    def status=(value); end

    sig { returns(T::Boolean) }
    def status?; end

    sig { returns(T.nilable(::String)) }
    def status_before_last_save; end

    sig { returns(T.untyped) }
    def status_before_type_cast; end

    sig { returns(T::Boolean) }
    def status_came_from_user?; end

    sig { returns(T.nilable([::String, ::String])) }
    def status_change; end

    sig { returns(T.nilable([::String, ::String])) }
    def status_change_to_be_saved; end

    sig { params(from: ::String, to: ::String).returns(T::Boolean) }
    def status_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def status_in_database; end

    sig { returns(T.nilable([::String, ::String])) }
    def status_previous_change; end

    sig { params(from: ::String, to: ::String).returns(T::Boolean) }
    def status_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def status_previously_was; end

    sig { returns(T.nilable(::String)) }
    def status_was; end

    sig { void }
    def status_will_change!; end

    sig { returns(T.nilable(::ActiveSupport::TimeWithZone)) }
    def submitted_at; end

    sig { params(value: T.nilable(::ActiveSupport::TimeWithZone)).returns(T.nilable(::ActiveSupport::TimeWithZone)) }
    def submitted_at=(value); end

    sig { returns(T::Boolean) }
    def submitted_at?; end

    sig { returns(T.nilable(::ActiveSupport::TimeWithZone)) }
    def submitted_at_before_last_save; end

    sig { returns(T.untyped) }
    def submitted_at_before_type_cast; end

    sig { returns(T::Boolean) }
    def submitted_at_came_from_user?; end

    sig { returns(T.nilable([T.nilable(::ActiveSupport::TimeWithZone), T.nilable(::ActiveSupport::TimeWithZone)])) }
    def submitted_at_change; end

    sig { returns(T.nilable([T.nilable(::ActiveSupport::TimeWithZone), T.nilable(::ActiveSupport::TimeWithZone)])) }
    def submitted_at_change_to_be_saved; end

    sig do
      params(
        from: T.nilable(::ActiveSupport::TimeWithZone),
        to: T.nilable(::ActiveSupport::TimeWithZone)
      ).returns(T::Boolean)
    end
    def submitted_at_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::ActiveSupport::TimeWithZone)) }
    def submitted_at_in_database; end

    sig { returns(T.nilable([T.nilable(::ActiveSupport::TimeWithZone), T.nilable(::ActiveSupport::TimeWithZone)])) }
    def submitted_at_previous_change; end

    sig do
      params(
        from: T.nilable(::ActiveSupport::TimeWithZone),
        to: T.nilable(::ActiveSupport::TimeWithZone)
      ).returns(T::Boolean)
    end
    def submitted_at_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::ActiveSupport::TimeWithZone)) }
    def submitted_at_previously_was; end

    sig { returns(T.nilable(::ActiveSupport::TimeWithZone)) }
    def submitted_at_was; end

    sig { void }
    def submitted_at_will_change!; end

    sig { returns(T.nilable(::String)) }
    def tracking_number; end

    sig { params(value: T.nilable(::String)).returns(T.nilable(::String)) }
    def tracking_number=(value); end

    sig { returns(T::Boolean) }
    def tracking_number?; end

    sig { returns(T.nilable(::String)) }
    def tracking_number_before_last_save; end

    sig { returns(T.untyped) }
    def tracking_number_before_type_cast; end

    sig { returns(T::Boolean) }
    def tracking_number_came_from_user?; end

    sig { returns(T.nilable([T.nilable(::String), T.nilable(::String)])) }
    def tracking_number_change; end

    sig { returns(T.nilable([T.nilable(::String), T.nilable(::String)])) }
    def tracking_number_change_to_be_saved; end

    sig { params(from: T.nilable(::String), to: T.nilable(::String)).returns(T::Boolean) }
    def tracking_number_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def tracking_number_in_database; end

    sig { returns(T.nilable([T.nilable(::String), T.nilable(::String)])) }
    def tracking_number_previous_change; end

    sig { params(from: T.nilable(::String), to: T.nilable(::String)).returns(T::Boolean) }
    def tracking_number_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def tracking_number_previously_was; end

    sig { returns(T.nilable(::String)) }
    def tracking_number_was; end

    sig { void }
    def tracking_number_will_change!; end

    sig { returns(::ActiveSupport::TimeWithZone) }
    def updated_at; end

    sig { params(value: ::ActiveSupport::TimeWithZone).returns(::ActiveSupport::TimeWithZone) }
    def updated_at=(value); end

    sig { returns(T::Boolean) }
    def updated_at?; end

    sig { returns(T.nilable(::ActiveSupport::TimeWithZone)) }
    def updated_at_before_last_save; end

    sig { returns(T.untyped) }
    def updated_at_before_type_cast; end

    sig { returns(T::Boolean) }
    def updated_at_came_from_user?; end

    sig { returns(T.nilable([::ActiveSupport::TimeWithZone, ::ActiveSupport::TimeWithZone])) }
    def updated_at_change; end

    sig { returns(T.nilable([::ActiveSupport::TimeWithZone, ::ActiveSupport::TimeWithZone])) }
    def updated_at_change_to_be_saved; end

    sig { params(from: ::ActiveSupport::TimeWithZone, to: ::ActiveSupport::TimeWithZone).returns(T::Boolean) }
    def updated_at_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::ActiveSupport::TimeWithZone)) }
    def updated_at_in_database; end

    sig { returns(T.nilable([::ActiveSupport::TimeWithZone, ::ActiveSupport::TimeWithZone])) }
    def updated_at_previous_change; end

    sig { params(from: ::ActiveSupport::TimeWithZone, to: ::ActiveSupport::TimeWithZone).returns(T::Boolean) }
    def updated_at_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::ActiveSupport::TimeWithZone)) }
    def updated_at_previously_was; end

    sig { returns(T.nilable(::ActiveSupport::TimeWithZone)) }
    def updated_at_was; end

    sig { void }
    def updated_at_will_change!; end

    sig { returns(::Integer) }
    def user_id; end

    sig { params(value: ::Integer).returns(::Integer) }
    def user_id=(value); end

    sig { returns(T::Boolean) }
    def user_id?; end

    sig { returns(T.nilable(::Integer)) }
    def user_id_before_last_save; end

    sig { returns(T.untyped) }
    def user_id_before_type_cast; end

    sig { returns(T::Boolean) }
    def user_id_came_from_user?; end

    sig { returns(T.nilable([::Integer, ::Integer])) }
    def user_id_change; end

    sig { returns(T.nilable([::Integer, ::Integer])) }
    def user_id_change_to_be_saved; end

    sig { params(from: ::Integer, to: ::Integer).returns(T::Boolean) }
    def user_id_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::Integer)) }
    def user_id_in_database; end

    sig { returns(T.nilable([::Integer, ::Integer])) }
    def user_id_previous_change; end

    sig { params(from: ::Integer, to: ::Integer).returns(T::Boolean) }
    def user_id_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::Integer)) }
    def user_id_previously_was; end

    sig { returns(T.nilable(::Integer)) }
    def user_id_was; end

    sig { void }
    def user_id_will_change!; end

    sig { returns(T::Boolean) }
    def will_save_change_to_base_cents?; end

    sig { returns(T::Boolean) }
    def will_save_change_to_charged_cents?; end

    sig { returns(T::Boolean) }
    def will_save_change_to_contact_id?; end

    sig { returns(T::Boolean) }
    def will_save_change_to_created_at?; end

    sig { returns(T::Boolean) }
    def will_save_change_to_failure_reason?; end

    sig { returns(T::Boolean) }
    def will_save_change_to_holiday_card_id?; end

    sig { returns(T::Boolean) }
    def will_save_change_to_id?; end

    sig { returns(T::Boolean) }
    def will_save_change_to_id_value?; end

    sig { returns(T::Boolean) }
    def will_save_change_to_idempotency_key?; end

    sig { returns(T::Boolean) }
    def will_save_change_to_mailed_at?; end

    sig { returns(T::Boolean) }
    def will_save_change_to_mailing_class?; end

    sig { returns(T::Boolean) }
    def will_save_change_to_postage_credit_id?; end

    sig { returns(T::Boolean) }
    def will_save_change_to_postgrid_id?; end

    sig { returns(T::Boolean) }
    def will_save_change_to_rate_card_version?; end

    sig { returns(T::Boolean) }
    def will_save_change_to_recipient_snapshot?; end

    sig { returns(T::Boolean) }
    def will_save_change_to_size?; end

    sig { returns(T::Boolean) }
    def will_save_change_to_status?; end

    sig { returns(T::Boolean) }
    def will_save_change_to_submitted_at?; end

    sig { returns(T::Boolean) }
    def will_save_change_to_tracking_number?; end

    sig { returns(T::Boolean) }
    def will_save_change_to_updated_at?; end

    sig { returns(T::Boolean) }
    def will_save_change_to_user_id?; end

    sig { returns(T::Boolean) }
    def will_save_change_to_zone?; end

    sig { returns(::String) }
    def zone; end

    sig { params(value: ::String).returns(::String) }
    def zone=(value); end

    sig { returns(T::Boolean) }
    def zone?; end

    sig { returns(T.nilable(::String)) }
    def zone_before_last_save; end

    sig { returns(T.untyped) }
    def zone_before_type_cast; end

    sig { returns(T::Boolean) }
    def zone_came_from_user?; end

    sig { returns(T.nilable([::String, ::String])) }
    def zone_change; end

    sig { returns(T.nilable([::String, ::String])) }
    def zone_change_to_be_saved; end

    sig { params(from: ::String, to: ::String).returns(T::Boolean) }
    def zone_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def zone_in_database; end

    sig { returns(T.nilable([::String, ::String])) }
    def zone_previous_change; end

    sig { params(from: ::String, to: ::String).returns(T::Boolean) }
    def zone_previously_changed?(from: T.unsafe(nil), to: T.unsafe(nil)); end

    sig { returns(T.nilable(::String)) }
    def zone_previously_was; end

    sig { returns(T.nilable(::String)) }
    def zone_was; end

    sig { void }
    def zone_will_change!; end
  end

  module GeneratedRelationMethods
    sig { returns(PrivateRelation) }
    def all; end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def and(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def annotate(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def arel_columns(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def create_with(*args, &blk); end

    sig { params(value: T::Boolean).returns(PrivateRelation) }
    def distinct(value = true); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def eager_load(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def except(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def excluding(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def extending(*args, &blk); end

    sig { params(association: Symbol).returns(T::Array[T.untyped]) }
    def extract_associated(association); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def for_card(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def from(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelationGroupChain) }
    def group(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def having(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def in_order_of(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def includes(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def invert_where(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def joins(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def left_joins(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def left_outer_joins(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def limit(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def lock(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def merge(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def newest_first(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def none(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def null_relation?(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def offset(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def only(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def optimizer_hints(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def or(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def order(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def preload(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def readonly(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def references(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def regroup(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def reorder(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def reselect(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def reverse_order(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def rewhere(*args, &blk); end

    sig { params(args: T.untyped).returns(PrivateRelation) }
    sig do
      params(
        blk: T.proc.params(record: ::HolidayCardMailOrder).returns(BasicObject)
      ).returns(T::Array[::HolidayCardMailOrder])
    end
    def select(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def strict_loading(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def structurally_compatible?(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def uniq!(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def unscope(*args, &blk); end

    sig { returns(PrivateRelationWhereChain) }
    sig { params(args: T.untyped).returns(PrivateRelation) }
    def where(*args); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def with(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def with_recursive(*args, &blk); end

    sig { params(args: T.untyped, blk: T.untyped).returns(PrivateRelation) }
    def without(*args, &blk); end
  end

  class PrivateAssociationRelation < ::ActiveRecord::AssociationRelation
    include CommonRelationMethods
    include GeneratedAssociationRelationMethods

    Elem = type_member { { fixed: ::HolidayCardMailOrder } }

    sig { returns(T::Array[::HolidayCardMailOrder]) }
    def to_a; end

    sig { returns(T::Array[::HolidayCardMailOrder]) }
    def to_ary; end
  end

  class PrivateAssociationRelationGroupChain < PrivateAssociationRelation
    Elem = type_member { { fixed: ::HolidayCardMailOrder } }

    sig { params(column_name: T.any(String, Symbol)).returns(T::Hash[T.untyped, T.any(Integer, Float, BigDecimal)]) }
    def average(column_name); end

    sig do
      params(
        operation: Symbol,
        column_name: T.any(String, Symbol)
      ).returns(T::Hash[T.untyped, T.any(Integer, Float, BigDecimal)])
    end
    def calculate(operation, column_name); end

    sig { params(column_name: T.untyped).returns(T::Hash[T.untyped, Integer]) }
    def count(column_name = nil); end

    sig { params(args: T.untyped, blk: T.untyped).returns(T.self_type) }
    def having(*args, &blk); end

    sig { params(column_name: T.any(String, Symbol)).returns(T::Hash[T.untyped, T.untyped]) }
    def maximum(column_name); end

    sig { params(column_name: T.any(String, Symbol)).returns(T::Hash[T.untyped, T.untyped]) }
    def minimum(column_name); end

    sig { returns(T::Hash[T.untyped, Integer]) }
    def size; end

    sig do
      params(
        column_name: T.nilable(T.any(String, Symbol)),
        block: T.nilable(T.proc.params(record: T.untyped).returns(T.untyped))
      ).returns(T::Hash[T.untyped, T.any(Integer, Float, BigDecimal)])
    end
    def sum(column_name = nil, &block); end
  end

  class PrivateAssociationRelationWhereChain
    Elem = type_member { { fixed: ::HolidayCardMailOrder } }

    sig { params(args: T.untyped).returns(PrivateAssociationRelation) }
    def associated(*args); end

    sig { params(args: T.untyped).returns(PrivateAssociationRelation) }
    def missing(*args); end

    sig { params(opts: T.untyped, rest: T.untyped).returns(PrivateAssociationRelation) }
    def not(opts, *rest); end
  end

  class PrivateCollectionProxy < ::ActiveRecord::Associations::CollectionProxy
    include CommonRelationMethods
    include GeneratedAssociationRelationMethods

    Elem = type_member { { fixed: ::HolidayCardMailOrder } }

    sig do
      params(
        records: T.any(::HolidayCardMailOrder, T::Enumerable[T.any(::HolidayCardMailOrder, T::Enumerable[::HolidayCardMailOrder])])
      ).returns(PrivateCollectionProxy)
    end
    def <<(*records); end

    sig do
      params(
        records: T.any(::HolidayCardMailOrder, T::Enumerable[T.any(::HolidayCardMailOrder, T::Enumerable[::HolidayCardMailOrder])])
      ).returns(PrivateCollectionProxy)
    end
    def append(*records); end

    sig { returns(PrivateCollectionProxy) }
    def clear; end

    sig do
      params(
        records: T.any(::HolidayCardMailOrder, T::Enumerable[T.any(::HolidayCardMailOrder, T::Enumerable[::HolidayCardMailOrder])])
      ).returns(PrivateCollectionProxy)
    end
    def concat(*records); end

    sig { returns(T::Array[::HolidayCardMailOrder]) }
    def load_target; end

    sig do
      params(
        records: T.any(::HolidayCardMailOrder, T::Enumerable[T.any(::HolidayCardMailOrder, T::Enumerable[::HolidayCardMailOrder])])
      ).returns(PrivateCollectionProxy)
    end
    def prepend(*records); end

    sig do
      params(
        records: T.any(::HolidayCardMailOrder, T::Enumerable[T.any(::HolidayCardMailOrder, T::Enumerable[::HolidayCardMailOrder])])
      ).returns(PrivateCollectionProxy)
    end
    def push(*records); end

    sig do
      params(
        other_array: T.any(::HolidayCardMailOrder, T::Enumerable[T.any(::HolidayCardMailOrder, T::Enumerable[::HolidayCardMailOrder])])
      ).returns(T::Array[::HolidayCardMailOrder])
    end
    def replace(other_array); end

    sig { returns(PrivateAssociationRelation) }
    def scope; end

    sig { returns(T::Array[::HolidayCardMailOrder]) }
    def target; end

    sig { returns(T::Array[::HolidayCardMailOrder]) }
    def to_a; end

    sig { returns(T::Array[::HolidayCardMailOrder]) }
    def to_ary; end
  end

  class PrivateRelation < ::ActiveRecord::Relation
    include CommonRelationMethods
    include GeneratedRelationMethods

    Elem = type_member { { fixed: ::HolidayCardMailOrder } }

    sig { returns(T::Array[::HolidayCardMailOrder]) }
    def to_a; end

    sig { returns(T::Array[::HolidayCardMailOrder]) }
    def to_ary; end
  end

  class PrivateRelationGroupChain < PrivateRelation
    Elem = type_member { { fixed: ::HolidayCardMailOrder } }

    sig { params(column_name: T.any(String, Symbol)).returns(T::Hash[T.untyped, T.any(Integer, Float, BigDecimal)]) }
    def average(column_name); end

    sig do
      params(
        operation: Symbol,
        column_name: T.any(String, Symbol)
      ).returns(T::Hash[T.untyped, T.any(Integer, Float, BigDecimal)])
    end
    def calculate(operation, column_name); end

    sig { params(column_name: T.untyped).returns(T::Hash[T.untyped, Integer]) }
    def count(column_name = nil); end

    sig { params(args: T.untyped, blk: T.untyped).returns(T.self_type) }
    def having(*args, &blk); end

    sig { params(column_name: T.any(String, Symbol)).returns(T::Hash[T.untyped, T.untyped]) }
    def maximum(column_name); end

    sig { params(column_name: T.any(String, Symbol)).returns(T::Hash[T.untyped, T.untyped]) }
    def minimum(column_name); end

    sig { returns(T::Hash[T.untyped, Integer]) }
    def size; end

    sig do
      params(
        column_name: T.nilable(T.any(String, Symbol)),
        block: T.nilable(T.proc.params(record: T.untyped).returns(T.untyped))
      ).returns(T::Hash[T.untyped, T.any(Integer, Float, BigDecimal)])
    end
    def sum(column_name = nil, &block); end
  end

  class PrivateRelationWhereChain
    Elem = type_member { { fixed: ::HolidayCardMailOrder } }

    sig { params(args: T.untyped).returns(PrivateRelation) }
    def associated(*args); end

    sig { params(args: T.untyped).returns(PrivateRelation) }
    def missing(*args); end

    sig { params(opts: T.untyped, rest: T.untyped).returns(PrivateRelation) }
    def not(opts, *rest); end
  end
end
