# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `HolidayCardMailSubmissionJob`.
# Please instead update this file by running `bin/tapioca dsl HolidayCardMailSubmissionJob`.


class HolidayCardMailSubmissionJob
  class << self
    sig do
      params(
        order_id: T.untyped,
        block: T.nilable(T.proc.params(job: HolidayCardMailSubmissionJob).void)
      ).returns(T.any(HolidayCardMailSubmissionJob, FalseClass))
    end
    def perform_later(order_id, &block); end

    sig { params(order_id: T.untyped).returns(T.untyped) }
    def perform_now(order_id); end
  end
end
