# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `NotifyRsvpsOfUpdateJob`.
# Please instead update this file by running `bin/tapioca dsl NotifyRsvpsOfUpdateJob`.


class NotifyRsvpsOfUpdateJob
  class << self
    sig do
      params(
        invitation_id: T.untyped,
        block: T.nilable(T.proc.params(job: NotifyRsvpsOfUpdateJob).void)
      ).returns(T.any(NotifyRsvpsOfUpdateJob, FalseClass))
    end
    def perform_later(invitation_id, &block); end

    sig { params(invitation_id: T.untyped).returns(T.untyped) }
    def perform_now(invitation_id); end
  end
end
