# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `OccasionReminderJob`.
# Please instead update this file by running `bin/tapioca dsl OccasionReminderJob`.


class OccasionReminderJob
  class << self
    sig do
      params(
        block: T.nilable(T.proc.params(job: OccasionReminderJob).void)
      ).returns(T.any(OccasionReminderJob, FalseClass))
    end
    def perform_later(&block); end

    sig { returns(T.untyped) }
    def perform_now; end
  end
end
