# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `OccasionReminderMailer`.
# Please instead update this file by running `bin/tapioca dsl OccasionReminderMailer`.


class OccasionReminderMailer
  class << self
    sig { params(occasion: T.untyped).returns(::ActionMailer::MessageDelivery) }
    def upcoming_occasion(occasion); end
  end
end
