# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `OrganizationMailer`.
# Please instead update this file by running `bin/tapioca dsl OrganizationMailer`.


class OrganizationMailer
  class << self
    sig { params(organization_invitation: T.untyped).returns(::ActionMailer::MessageDelivery) }
    def invitation(organization_invitation); end
  end
end
