# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PasswordResetMailer`.
# Please instead update this file by running `bin/tapioca dsl PasswordResetMailer`.


class PasswordResetMailer
  class << self
    sig { returns(::ActionMailer::MessageDelivery) }
    def send_reset_email; end
  end
end
