# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PostgridWebhookJob`.
# Please instead update this file by running `bin/tapioca dsl PostgridWebhookJob`.


class PostgridWebhookJob
  class << self
    sig do
      params(
        postgrid_id: T.untyped,
        postgrid_status: T.untyped,
        tracking_number: T.untyped,
        block: T.nilable(T.proc.params(job: PostgridWebhookJob).void)
      ).returns(T.any(PostgridWebhookJob, FalseClass))
    end
    def perform_later(postgrid_id:, postgrid_status: T.unsafe(nil), tracking_number: T.unsafe(nil), &block); end

    sig { params(postgrid_id: T.untyped, postgrid_status: T.untyped, tracking_number: T.untyped).returns(T.untyped) }
    def perform_now(postgrid_id:, postgrid_status: T.unsafe(nil), tracking_number: T.unsafe(nil)); end
  end
end
