# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `RsvpMailer`.
# Please instead update this file by running `bin/tapioca dsl RsvpMailer`.


class RsvpMailer
  class << self
    sig { params(rsvp: T.untyped).returns(::ActionMailer::MessageDelivery) }
    def guest_confirmation(rsvp); end

    sig { params(rsvp: T.untyped, is_update: T.untyped).returns(::ActionMailer::MessageDelivery) }
    def host_notification(rsvp, is_update: T.unsafe(nil)); end

    sig { params(rsvp: T.untyped).returns(::ActionMailer::MessageDelivery) }
    def invitation_updated(rsvp); end
  end
end
