# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `SupportMailer`.
# Please instead update this file by running `bin/tapioca dsl SupportMailer`.


class SupportMailer
  class << self
    sig do
      params(
        reason: T.untyped,
        message: T.untyped,
        user_email: T.untyped
      ).returns(::ActionMailer::MessageDelivery)
    end
    def send_case_email(reason, message, user_email); end
  end
end
