# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `SupportTicketMailer`.
# Please instead update this file by running `bin/tapioca dsl SupportTicketMailer`.


class SupportTicketMailer
  class << self
    sig { params(support_ticket_message: T.untyped).returns(::ActionMailer::MessageDelivery) }
    def admin_reply(support_ticket_message); end
  end
end
