# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `UserMailer`.
# Please instead update this file by running `bin/tapioca dsl UserMailer`.


class UserMailer
  class << self
    sig { params(user: T.untyped).returns(::ActionMailer::MessageDelivery) }
    def confirmation_code(user:); end

    sig { params(user: T.untyped, amount: T.untyped).returns(::ActionMailer::MessageDelivery) }
    def purchase_confirmation_email(user, amount); end
  end
end
