# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Types::OpeningMessageTextInputType`.
# Please instead update this file by running `bin/tapioca dsl Types::OpeningMessageTextInputType`.


class Types::OpeningMessageTextInputType
  sig { returns(T.nilable(::String)) }
  def subtitle; end

  sig { returns(::String) }
  def title; end
end
