# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Types::OpeningMessageConfigInputType`.
# Please instead update this file by running `bin/tapioca dsl Types::OpeningMessageConfigInputType`.


class Types::OpeningMessageConfigInputType
  sig { returns(T.nilable(::Types::OpeningMessageAnimationInputType)) }
  def animation; end

  sig { returns(T.nilable(::Types::OpeningMessageBackgroundInputType)) }
  def background; end

  sig { returns(T.nilable(::String)) }
  def template_id; end

  sig { returns(::Types::OpeningMessageTextInputType) }
  def text; end

  sig { returns(T.nilable(::Types::OpeningMessageThemeInputType)) }
  def theme; end
end
