# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Types::OpeningMessageThemeInputType`.
# Please instead update this file by running `bin/tapioca dsl Types::OpeningMessageThemeInputType`.


class Types::OpeningMessageThemeInputType
  sig { returns(T.nilable(::String)) }
  def font; end

  sig { returns(T.nilable(::String)) }
  def text_color; end
end
