# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Types::OpeningMessageAnimationInputType`.
# Please instead update this file by running `bin/tapioca dsl Types::OpeningMessageAnimationInputType`.


class Types::OpeningMessageAnimationInputType
  sig { returns(T.nilable(::Integer)) }
  def duration_ms; end

  sig { returns(T.nilable(::String)) }
  def preset; end
end
