# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Types::OpeningMessageBackgroundInputType`.
# Please instead update this file by running `bin/tapioca dsl Types::OpeningMessageBackgroundInputType`.


class Types::OpeningMessageBackgroundInputType
  sig { returns(T.nilable(::Float)) }
  def overlay_opacity; end

  sig { returns(::String) }
  def type; end

  sig { returns(::String) }
  def value; end
end
