# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Types::WishListItemInputType`.
# Please instead update this file by running `bin/tapioca dsl Types::WishListItemInputType`.


class Types::WishListItemInputType
  sig { returns(T.nilable(::String)) }
  def image_url; end

  sig { returns(T.nilable(::String)) }
  def note; end

  sig { returns(T.nilable(::String)) }
  def price; end

  sig { returns(T.nilable(::Integer)) }
  def quantity; end

  sig { returns(T.nilable(::String)) }
  def store; end

  sig { returns(::String) }
  def title; end

  sig { returns(T.nilable(::String)) }
  def url; end
end
