# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Types::WishListContributionInputType`.
# Please instead update this file by running `bin/tapioca dsl Types::WishListContributionInputType`.


class Types::WishListContributionInputType
  sig { returns(::String) }
  def handle; end

  sig { returns(::String) }
  def kind; end

  sig { returns(T.nilable(::String)) }
  def label; end

  sig { returns(T.nilable(::String)) }
  def note; end

  sig { returns(T.nilable(::String)) }
  def suggested_amount; end
end
