# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `action_text-trix` gem.
# Please instead update this file by running `bin/tapioca gem action_text-trix`.


# source://action_text-trix//lib/action_text/trix/version.rb#1
module Trix; end

# source://action_text-trix//lib/action_text/trix/engine.rb#2
class Trix::Engine < ::Rails::Engine
  # source://activesupport/8.1.2/lib/active_support/callbacks.rb#915
  def _run_load_seed_callbacks(&block); end

  class << self
    private

    # source://activesupport/8.1.2/lib/active_support/class_attribute.rb#15
    def __class_attr___callbacks; end

    # source://activesupport/8.1.2/lib/active_support/class_attribute.rb#17
    def __class_attr___callbacks=(new_value); end
  end
end

# source://action_text-trix//lib/action_text/trix/version.rb#2
Trix::VERSION = T.let(T.unsafe(nil), String)
