# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `google-id-token` gem.
# Please instead update this file by running `bin/tapioca gem google-id-token`.


# source://google-id-token//lib/google-id-token/version.rb#1
module GoogleIDToken; end

# source://google-id-token//lib/google-id-token.rb#38
class GoogleIDToken::AudienceMismatchError < ::GoogleIDToken::ValidationError; end

# source://google-id-token//lib/google-id-token.rb#33
class GoogleIDToken::CertificateError < ::StandardError; end

# source://google-id-token//lib/google-id-token.rb#39
class GoogleIDToken::ClientIDMismatchError < ::GoogleIDToken::ValidationError; end

# source://google-id-token//lib/google-id-token.rb#35
class GoogleIDToken::ExpiredTokenError < ::GoogleIDToken::ValidationError; end

# source://google-id-token//lib/google-id-token.rb#37
class GoogleIDToken::InvalidIssuerError < ::GoogleIDToken::ValidationError; end

# source://google-id-token//lib/google-id-token.rb#36
class GoogleIDToken::SignatureError < ::GoogleIDToken::ValidationError; end

# source://google-id-token//lib/google-id-token/version.rb#2
GoogleIDToken::VERSION = T.let(T.unsafe(nil), String)

# source://google-id-token//lib/google-id-token.rb#34
class GoogleIDToken::ValidationError < ::StandardError; end

# source://google-id-token//lib/google-id-token.rb#41
class GoogleIDToken::Validator
  include ::MonitorMixin

  # @return [Validator] a new instance of Validator
  #
  # source://google-id-token//lib/google-id-token.rb#50
  def initialize(options = T.unsafe(nil)); end

  # If it validates, returns a hash with the JWT payload from the ID Token.
  #  You have to provide an "aud" value, which must match the
  #  token's field with that name, and will similarly check cid if provided.
  #
  # If something fails, raises an error
  #
  # @param token [String] The string form of the token
  # @param aud [String] The required audience value
  # @param cid [String] The optional client-id ("azp" field) value
  # @return [Hash] The decoded ID token
  #
  # source://google-id-token//lib/google-id-token.rb#82
  def check(token, aud, cid = T.unsafe(nil)); end

  private

  # @return [Boolean]
  #
  # source://google-id-token//lib/google-id-token.rb#183
  def certs_cache_expired?; end

  # tries to validate the token against each cached cert.
  # Returns the token payload or raises a ValidationError or
  #  nil, which means none of the certs validated.
  #
  # source://google-id-token//lib/google-id-token.rb#108
  def check_cached_certs(token, aud, cid); end

  # source://google-id-token//lib/google-id-token.rb#162
  def old_skool_refresh_certs; end

  # returns false if there was a problem
  #
  # source://google-id-token//lib/google-id-token.rb#151
  def refresh_certs; end
end

# 1 hour
#
# source://google-id-token//lib/google-id-token.rb#45
GoogleIDToken::Validator::GOOGLE_CERTS_EXPIRY = T.let(T.unsafe(nil), Integer)

# source://google-id-token//lib/google-id-token.rb#44
GoogleIDToken::Validator::GOOGLE_CERTS_URI = T.let(T.unsafe(nil), String)

# https://developers.google.com/identity/sign-in/web/backend-auth
#
# source://google-id-token//lib/google-id-token.rb#48
GoogleIDToken::Validator::GOOGLE_ISSUERS = T.let(T.unsafe(nil), Array)
