name: Admin CI

on:
  pull_request:
    paths:
      - 'admin/**'

jobs:
  lint-build-nextjs:
    name: Lint, Format Check, and Build
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: admin

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'
          cache-dependency-path: admin/yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint (ESLint)
        run: yarn lint

      - name: Format Check (Prettier)
        run: yarn format-check

      - name: Build React app
        run: yarn build
